# Generated by Django 3.2 on 2021-04-09 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='q_a',
            name='ques',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=150)),
                ('score', models.FloatField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.blog')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.domain')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.project')),
                ('q_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.q_a')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.technology')),
            ],
        ),
    ]
