# Generated by Django 3.2 on 2021-04-14 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20210409_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='QA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'verbose_name': 'QA',
                'verbose_name_plural': 'QAs',
            },
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='developer',
            options={'verbose_name': 'Developer', 'verbose_name_plural': 'Developers'},
        ),
        migrations.AlterModelOptions(
            name='domain',
            options={'verbose_name': 'Domain', 'verbose_name_plural': 'Domains'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name': 'Technology', 'verbose_name_plural': 'Technologies'},
        ),
        migrations.RemoveField(
            model_name='developer',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='project',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='q_a',
        ),
        migrations.AddField(
            model_name='developer',
            name='blogs',
            field=models.ManyToManyField(to='data.Blog'),
        ),
        migrations.AddField(
            model_name='developer',
            name='projects',
            field=models.ManyToManyField(to='data.Project'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='developer',
            name='domain',
        ),
        migrations.AddField(
            model_name='developer',
            name='domain',
            field=models.ManyToManyField(to='data.Domain'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='developer',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='developer',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='developer',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='developer',
            name='technology',
        ),
        migrations.AddField(
            model_name='developer',
            name='technology',
            field=models.ManyToManyField(to='data.Technology'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Q_A',
        ),
        migrations.AddField(
            model_name='developer',
            name='qa',
            field=models.ManyToManyField(to='data.QA'),
        ),
    ]
